version: "3.3"
services:
  automatic-ripping-machine:
    container_name: arm-ripper
    devices:
      - "/dev/sr0:/dev/sr0"
    environment:
      - GID=1000
      - UID=1000
      - TZ=America/Chicago
    hostname: arm-ripper
    image: "1337server/automatic-ripping-machine:latest"
    ports:
      - "8585:8080/tcp"
    privileged: true
    restart: always
    networks:
      - archon
    volumes:
      - "/home/archon/arm:/home/arm"
      - "/home/archon/arm/logs:/home/arm/logs"
      - "/home/archon/arm/config:/home/arm/config"
      - "/srv/media/downloads/arm-media/music:/home/arm/Music"
      - "/srv/media/downloads/arm-media:/home/arm/media"


networks:
  archon:
    external: true
