version: "3.3"
services:
  bazarr:
    container_name: bazarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    hostname: bazarr
    image: "sekkr1/bazarr-subsync:latest"
    networks:
      - archon
    ports:
      - "6767:6767/tcp"
    restart: unless-stopped
    volumes:
      - "${DOCKER_CONFIG_PATH_BAZARR}:/config"
      - "${DOWNLOAD_PATH_TV}:/libraries/tv"
      - "${DOWNLOAD_PATH_MOVIES}:/libraries/movies"
networks:
  archon:
    external: true
