version: "3.3"
services:
  amvd:
    container_name: amvd
    environment:
      - AUTOSTART=true
      - CountryCode=us
      - FilePermissions=644
      - FolderPermissions=755
      - LidarrAPIkey=${LIDDAR_APIKEY}
      - LidarrUrl=http://lidarr:8686
      - MBRAINZMIRROR=https://musicbrainz.org
      - MBRATELIMIT=1
      - PGID=1000
      - PUID=1000
      - RequireVideoMatch=true
      - SCRIPTINTERVAL=1h
      - SOURCE_CONNECTION=lidarr
      - subtitlelanguage=en
      - TZ=${TZ}
      - USEFOLDERS=true
      - USEVIDEOFOLDERS=true
      - videofilter=live
      - WriteNFOs=true
    hostname: amd
    image: "randomninjaatk/amvd:latest"
    networks:
      - archon
    restart: unless-stopped
    volumes:
      - "${DOCKER_CONFIG_PATH}:/config"
      - "${DOWNLOAD_PATH_MUSIC}:/downloads-amvd"

networks:
  archon:
    external: true
