version: "3.3"
services:
  automatic-ripping-machine:
    container_name: arm-ripper
    devices:
      - "/dev/sr0:/dev/sr0"
    environment:
      - GID=1000
      - UID=1000
      - TZ=${TZ}
    hostname: arm-ripper
    image: "1337server/automatic-ripping-machine:latest"
    ports:
      - "8585:8080/tcp"
    privileged: true
    restart: always
    networks:
      - archon
    volumes:
      - "${DOCKER_CONFIG_PATH_AMD}:/home/arm"
      - "${DOCKER_CONFIG_PATH_AMD}/config:/home/arm/config"
      - "${DOCKER_CONFIG_PATH_AMD}/logs:/home/arm/logs"
      - "{DOWNLOAD_PATH_ARM-MEDIA}:/home/arm/media"
      - "{DOWNLOAD_PATH_ARM-MEDIA}/music:/home/arm/Music"

networks:
  archon:
    external: true
