version: '3.3'
services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: "cr.portainer.io/portainer/portainer-ce:2.9.3"
    networks:
      - archon
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always
    volumes:
      - "/home/archon/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  archon:
    external: true
